% Plot lifetime-diagnostic accuracy metrics for Figure 4.
%
% The script summarizes the cell-level voltage-fit outputs generated by the
% lifetime diagnostic workflow. Each marker corresponds to one reference
% performance test for a cell, grouped by aging condition. The panels report
% capacity-estimation error, full-cell voltage RMSE, and dV/dQ RMSE as a
% function of measured charge capacity.

clear
close all
clc

script_dir = fileparts(mfilename('fullpath'));
data_dir = fullfile(script_dir, 'data', 'lifetime_summaries');
figure_dir = fullfile(script_dir, 'figures');
if ~exist(figure_dir, 'dir')
    mkdir(figure_dir);
end

groups = [
    struct('name',"Room 25°C", 'cells',[64,2,7,47,1,35,60],           'color',[0.2588 0.5059 0.6431], 'marker','o')
    struct('name',"Hot 45°C",  'cells',[17,25,72,17,25,72],           'color',[0.7647 0.3922 0.2235], 'marker','o')
    struct('name',"Cold 0°C",  'cells',[68,58,16,49,32],              'color',[0.3 0.3 0.3],          'marker','o')
    struct('name',"20–80%",    'cells',[22,75,26],                    'color',[0.5961 0.7451 0.8000], 'marker','^')
    struct('name',"15–95%",    'cells',[40,9,54],                     'color',[0.4392 0.6196 0.6980], 'marker','s')
    struct('name',"50–100%",   'cells',[19,55,11],                    'color',[0.6 0.6 0.6],          'marker','p')
    struct('name',"0–50%",     'cells',[20],                          'color',[0.9294 0.6941 0.1255], 'marker','o')
];

plot_metric_panel( ...
    data_dir, figure_dir, groups, ...
    "Qcc_max_meas", "C_est", ...
    "Capacity [Ah]", "Capacity Error [%]", ...
    "F4_1_capacity_error_pct.svg", ...
    true);

plot_metric_panel( ...
    data_dir, figure_dir, groups, ...
    "Qcc_max_meas", "rmse_v_global", ...
    "Capacity [Ah]", "Voltage RMSE [mV]", ...
    "F4_1_voltage_rmse.svg", ...
    false);

plot_metric_panel( ...
    data_dir, figure_dir, groups, ...
    "Qcc_max_meas", "rmse_dvdq_global", ...
    "Capacity [Ah]", "dV/dQ RMSE [mV/Ah]", ...
    "F4_1_dvdq_rmse.svg", ...
    false);

%% Helpers

function plot_metric_panel(data_dir, figure_dir, groups, x_name, y_name, x_label, y_label, output_name, is_capacity_error)
fig = figure('Position', [50, 50, 400, 300], 'Color', 'w');
ax = axes(fig);
hold(ax, 'on')
box(ax, 'on')
grid(ax, 'off')

all_y = [];

for g = 1:numel(groups)
    group = groups(g);

    for cell_id = group.cells
        summary = read_cell_summary(data_dir, cell_id);
        if isempty(summary)
            continue
        end

        required_columns = {char(x_name), char(y_name)};
        if ~all(ismember(required_columns, summary.Properties.VariableNames))
            fprintf('Skipping cell %03d for %s because the summary is missing %s or %s.\n', ...
                cell_id, y_label, x_name, y_name);
            continue
        end

        x = summary.(x_name);
        if is_capacity_error
            y = abs((summary.(y_name) - summary.(x_name)) ./ summary.(x_name) * 100);
            y_plot = y;
        else
            y = summary.(y_name);
            y_plot = 1000 * y;
        end

        [x_clean, y_clean, y_plot_clean] = remove_invalid_points(x, y, y_plot);
        all_y = [all_y; y_clean(:)]; %#ok<AGROW>

        plot(ax, x_clean, y_plot_clean, ...
            'LineStyle', 'none', ...
            'Marker', group.marker, ...
            'MarkerSize', 8, ...
            'MarkerFaceColor', group.color, ...
            'MarkerEdgeColor', 'none', ...
            'Color', group.color);
    end
end

rmse_value = sqrt(mean(all_y.^2, 'omitnan'));
if is_capacity_error
    yline(ax, rmse_value, '--');
    fprintf('Overall RMSE (%s): %.4f %%\n', y_label, rmse_value);
else
    yline(ax, 1000 * rmse_value, '--');
    fprintf('Overall RMSE (%s): %.6f\n', y_label, rmse_value);
end

set(ax, 'XDir', 'reverse');
ax.FontSize = 20;
xlabel(ax, x_label);
ylabel(ax, y_label);
set(fig, 'PaperPositionMode', 'auto');
print(fig, fullfile(figure_dir, output_name), '-dsvg', '-vector');
end

function summary = read_cell_summary(data_dir, cell_id)
cell_no = sprintf('%03d', cell_id);
file = fullfile(data_dir, "cell" + cell_no + "_voltage_fit_summary.csv");

if ~isfile(file)
    warning('Missing summary file for cell %s. Skipping.', cell_no);
    summary = [];
    return
end

summary = readtable(file);
end

function [x_out, y_out, y_plot_out] = remove_invalid_points(x_in, y_in, y_plot_in)
mask = isfinite(x_in) & isfinite(y_in) & isfinite(y_plot_in) & x_in ~= 0 & y_in ~= 0;
x_out = x_in;
y_out = y_in;
y_plot_out = y_plot_in;
x_out(~mask) = NaN;
y_out(~mask) = NaN;
y_plot_out(~mask) = NaN;
end
