% Plot pathway-dependent silicon current-share figure panels.
%
% This script consumes the CSV files generated by
% F2_BOL_EOL_CurrentShare.ipynb. For each eSOH scenario, it exports:
%   1) reconstructed full-cell voltage and electrode potentials,
%   2) material-resolved dQ/dV with silicon current share,
%   3) silicon and graphite lithiation capacities over SoC,
%   4) baseline and effective aged silicon OCP curves.

clear

script_dir = fileparts(mfilename('fullpath'));
data_folder = fullfile(script_dir, 'outputs', 'data');
figure_folder = fullfile(script_dir, 'outputs', 'figures');
if ~exist(figure_folder, 'dir')
    mkdir(figure_folder);
end

labels = ["BOL", "LLI", "LAM Si", "LAM NMC", "LAM Gr", "CELL20EOL", "LAM Si no deform"];

for i = 1:numel(labels)

label = labels(i);
data = readtable(fullfile(data_folder, label + "_eSOH_details_70EOL.csv"));

% Full-cell voltage, electrode potentials, and SoC exported from the
% eSOH reconstruction.
Q_exp = data.Q_exp;
V_fit = data.V_fit;
V_fit_anode = data.V_fit_anode;
V_fit_cathode = data.V_fit_cathode;
SoC = data.SoCs*100;

indice_eff = ~(isnan(V_fit_anode) & isnan(V_fit_cathode) & isnan(V_fit));

% dV/dQ and material-resolved dQ/dV traces on the common full-cell SoC axis.
dvdq_fit = data.dvdq_fit;
dvdq_fit_anode = data.dvdq_fit_anode;
dvdq_fit_cathode = data.dvdq_fit_cathode;

dqdv_fit_anode = data.dqdv_fit_anode;
dqdv_fit_cathode = data.dqdv_fit_cathode;

dqdv_fit = data.dqdv_fit;
dqdv_fit_si = data.dqdv_fit_si;

lim_max = max(Q_exp(indice_eff));
lim_min = min(Q_exp(indice_eff));

% Silicon and graphite lithiation capacities projected onto the same SoC axis.
si_Q = data.Q_si;
gr_Q = data.Q_gr;

%% Reconstructed full-cell voltage and electrode potentials
figure('Position', [50, 50, 350, 300]);
hold on

x1 = 0;
x2 = interp1(V_fit(~isnan(V_fit)),Q_exp(~isnan(V_fit)),4.199);
xline(x1,':')
xline(x2,':')

yl = [2,5];
x_fill = [x1 x2 x2 x1];
y_fill = [yl(1) yl(1) yl(2) yl(2)];
fill(x_fill, y_fill, [0.9 0.9 0.9], 'FaceAlpha', 0.2, 'EdgeColor', 'none');

plot(Q_exp, V_fit, 'Color', [0.1 0.1 0.1], 'LineWidth', 0.5, 'LineStyle', '-');

plot(Q_exp, V_fit_cathode, 'Color', [0.4275    0.3490    0.4784], 'LineWidth', 0.5, 'LineStyle', '-');

ax = gca;
ax.YLim = [2,5];
ax.FontSize = 20;
ax.XLabel.String = 'Capacity [Ah]';
ax.YLabel.String = 'Voltage & Potential [V]';
ax.XColor = [0.1 0.1 0.1];
ax.YColor = [0.1 0.1 0.1];


yyaxis right
plot(Q_exp, V_fit_anode, 'Color', [0.3294    0.4510    0.5569], 'LineWidth', 0.5, 'LineStyle', '-');


set(gca,'FontSize',14);
ax = gca;
xlim([lim_min-0.1, lim_max+0.1]);
ax.FontSize = 20;
ax.XLabel.String = 'Capacity [Ah]';
ax.YLabel.String = 'Potential [V]';
ax.YColor = [0.3294    0.4510    0.5569];
set(gcf,'color','w');
box on
titles = fullfile(figure_folder, "F2_Voltage_" + label + ".svg");
print(gcf, titles, '-dsvg', '-vector');

%% Material-resolved dQ/dV and silicon current share
figure('Position', [50, 50, 550, 300]);
yyaxis left
plot(SoC, -dqdv_fit_si./dqdv_fit*100, 'Color', [0.6353    0.3098    0.2745], 'LineWidth', 1, 'LineStyle', '-');
ax = gca;
xlim([0,100]);
ylim([0,100]);
ax.FontSize = 20;
ax.XLabel.String = 'SOC [%]';
ax.YLabel.String = 'Si current share [%]';
ax.XColor = [0.1 0.1 0.1];
ax.YColor = [0.6353    0.3098    0.2745];

yyaxis right
hold on
plot(SoC, -dqdv_fit, 'Color', [0.8 0.8 0.8], 'LineWidth', 0.5, 'LineStyle', '-');
plot(SoC, dqdv_fit_si, 'Color', [0.4980    0.6941    0.8000], 'LineWidth', 0.5, 'LineStyle', '-');

fill([SoC(~isnan(dqdv_fit_si))', flipud(SoC(~isnan(dqdv_fit_si)))'], [zeros(size(dqdv_fit_si(~isnan(dqdv_fit_si))))', flipud(dqdv_fit_si(~isnan(dqdv_fit_si)))'], ...
    [0.2588    0.5059    0.6431
], 'FaceAlpha', 0.1, 'EdgeColor', 'none');

dqdv_fit_gr = dqdv_fit+dqdv_fit_si;

plot(SoC,-dqdv_fit_gr , 'Color', [0.6510    0.6510    0.6510], 'LineWidth', 0.5, 'LineStyle', '-');

fill([SoC(~isnan(dqdv_fit_gr))', flipud(SoC(~isnan(dqdv_fit_gr)))'], [zeros(size(dqdv_fit_gr(~isnan(dqdv_fit_gr))))', flipud(-dqdv_fit_gr(~isnan(dqdv_fit_gr)))'], ...
    [0.6510    0.6510    0.6510], 'FaceAlpha', 0.1, 'EdgeColor', 'none');

ax = gca;
ax.YLim = [0,8];
ax.FontSize = 20;
ax.XLabel.String = 'SOC [%]';
ax.YLabel.String = 'dQ/dV [Ah/V]';
ax.XColor = [0.1 0.1 0.1];
ax.YColor = [0.1 0.1 0.1];

set(gcf,'color','w');
box on
titles = fullfile(figure_folder, "F2_ThermalManagement_" + label + ".svg");
print(gcf, titles, '-dsvg', '-vector');

%% Silicon and graphite lithiation capacity trajectories
figure('Position', [50, 50, 250, 300]);
tiledlayout(1, 1, 'TileSpacing', 'compact', 'Padding', 'compact');

hold on
plot(SoC, gr_Q, 'Color', [0.7 0.7 0.7], 'LineWidth', 0.5, 'LineStyle', '-');
plot(SoC, si_Q, 'Color', [0.2588    0.5059    0.6431], 'LineWidth', 0.5, 'LineStyle', '-');

ax = gca;
xlim([0,100]);
ax.FontSize = 20;
ax.XLabel.String = 'SOC [%]';
ax.YLabel.String = 'Q [Ah]';
ax.XColor = [0.1 0.1 0.1];
ax.YColor = [0.1 0.1 0.1];
set(gcf,'color','w');
box on
titles = fullfile(figure_folder, "F2_Thermal_Management_Sto_" + label + ".svg");
print(gcf, titles, '-dsvg', '-vector');

%% Effective silicon OCP evolution

si_ocp_cmp = readtable(fullfile(data_folder, label + "_Si_OCP_original_vs_reconstructed_deformed.csv"));

sto_common = si_ocp_cmp.sto_common;
p_si_original = si_ocp_cmp.p_si_original;
p_si_reconstructed_deformed = si_ocp_cmp.p_si_reconstructed_deformed;

figure('Position', [50, 50, 250, 300]);
tiledlayout(1, 1, 'TileSpacing', 'compact', 'Padding', 'compact');

hold on
plot(sto_common, p_si_original, ...
    'Color', [0.7 0.7 0.7], 'LineWidth', 0.5, 'LineStyle', '-');

plot(sto_common, p_si_reconstructed_deformed, ...
    'Color', [0.2588 0.5059 0.6431], 'LineWidth', 0.5, 'LineStyle', '-');

ax = gca;
xlim([0, 1]);
ylim([0, 0.5]);
ax.FontSize = 20;
ax.XLabel.String = 'Stoichiometry [-]';
ax.YLabel.String = 'Potential [V]';
ax.XColor = [0.1 0.1 0.1];
ax.YColor = [0.1 0.1 0.1];

set(gcf,'color','w');
box on
titles = fullfile(figure_folder, "F2_Si_OCP_Compare_" + label + ".svg");
print(gcf, titles, '-dsvg', '-vector');
end
