% Plot C-rate-dependent voltage and dV/dQ traces for Figure 5a.
%
% The plotted CSV files are generated by the C-rate diagnostic workflow
% (A02_crates_diagnostics.ipynb). BOL and EOL traces are shown separately to
% visualize rate-dependent voltage distortion and differential-capacity changes.

clear
close all
clc

script_dir = fileparts(mfilename('fullpath'));
repo_root = fullfile(script_dir, '..', '..', '..');
batch_root = fullfile(repo_root, 'code', 'diagnostic_algorithm_lifetime_crate', 'batch_results', 'A02_crate_diagnostics');
folder_bol = fullfile(batch_root, 'BOL_crate_diagnostics', 'plots');
folder_eol = fullfile(batch_root, 'EOL_crate_diagnostics', 'plots');
figure_dir = fullfile(script_dir, 'figures');
if ~exist(figure_dir, 'dir')
    mkdir(figure_dir);
end

crate_labels = {'C_100', 'C_20', 'C_10', 'C_5', 'C_3'};
legend_labels = {'C/100', 'C/20', 'C/10', 'C/5', 'C/3'};
colors = [
    0.3294 0.4510 0.5569
    0.4275 0.3490 0.4784
    0.6353 0.3098 0.2745
    0.4980 0.6941 0.8000
    0.6510 0.6510 0.6510
];

plot_trace_panel(folder_bol, crate_labels, legend_labels, colors, ...
    'voltage', 'F5_BOL_voltage.svg', figure_dir);
plot_trace_panel(folder_eol, crate_labels, legend_labels, colors, ...
    'voltage', 'F5_EOL_voltage.svg', figure_dir);
plot_trace_panel(folder_bol, crate_labels, legend_labels, colors, ...
    'dvdq', 'F5_BOL_dvdq.svg', figure_dir);
plot_trace_panel(folder_eol, crate_labels, legend_labels, colors, ...
    'dvdq', 'F5_EOL_dvdq.svg', figure_dir);

%% Helpers

function plot_trace_panel(data_folder, crate_labels, legend_labels, colors, panel_type, output_name, figure_dir)
fig = figure('Position', [50, 50, 350, 300], 'Color', 'w');
hold on
legend_entries = {};

for k = 1:numel(crate_labels)
    crate = crate_labels{k};
    if strcmp(panel_type, 'voltage')
        file = find_one_file(data_folder, ['*_' crate '_voltage_panel.csv']);
    else
        file = find_one_file(data_folder, ['*_' crate '_derivative_meas_native.csv']);
    end

    if strlength(file) == 0
        warning('Missing %s file for %s in %s.', panel_type, crate, data_folder);
        continue
    end

    data = readtable(file);
    if strcmp(panel_type, 'voltage')
        q = data.Q_meas;
        y = data.V_meas;
    else
        q = data.Q_meas_native;
        y = data.dVdQ_meas_native;
    end

    valid = isfinite(q) & isfinite(y);
    q = q(valid);
    y = y(valid);
    if isempty(q)
        continue
    end

    q = q - min(q);
    plot(q, y, 'LineWidth', 0.75, 'Color', colors(k, :));
    legend_entries{end + 1} = legend_labels{k}; %#ok<AGROW>
end

ax = gca;
ax.FontSize = 20;
ax.XLabel.String = 'Q [Ah]';
ax.XColor = [0.1 0.1 0.1];
ax.YColor = [0.1 0.1 0.1];
if strcmp(panel_type, 'voltage')
    ax.YLim = [2.5, 4.5];
    ax.YLabel.String = 'Voltage [V]';
    legend_location = 'southeast';
else
    ax.YLim = [0.1, 0.8];
    ax.YLabel.String = 'dV/dQ [V/Ah]';
    legend_location = 'northeast';
end
grid off
box on

legend_handle = legend(legend_entries);
legend_handle.FontSize = 16;
legend_handle.Location = legend_location;

set(fig, 'PaperPositionMode', 'auto');
print(fig, fullfile(figure_dir, output_name), '-dsvg', '-vector');
end

function file = find_one_file(folder, pattern)
files = dir(fullfile(folder, pattern));
if isempty(files)
    file = "";
    return
end
file = string(fullfile(files(1).folder, files(1).name));
end
