% Plot CRB-derived parameter error bounds versus sampling density for Figure 5b.
%
% The input CSV is generated by code/error_bound_analysis/error_bound_analysis_with_CRB.ipynb.
% This plotting copy reads that canonical output and writes the Figure 5b panels
% into the local f5/figures folder.

clear
close all
clc

script_dir = fileparts(mfilename('fullpath'));
repo_root = fullfile(script_dir, '..', '..', '..');
crb_output_dir = fullfile(repo_root, 'code', 'error_bound_analysis', 'outputs');
figure_dir = fullfile(script_dir, 'figures');
if ~exist(figure_dir, 'dir')
    mkdir(figure_dir);
end

data = readtable(fullfile(crb_output_dir, 'A03_Sampling_Points_Impact_BOL_inferred.csv'));
data.MAE = mean([data.Cn_Si, data.Cn_Gr, data.Cn, data.Cp, data.LI, data.a, data.b], 2, 'omitnan');

% The CRB CSV preserves internal column names a and b; these correspond to
% the manuscript's silicon-OCP deformation parameters s_V and U_{off}.
params = {'Cn_Si', 'Cn_Gr', 'Cn', 'Cp', 'LI', 'a', 'b', 'MAE'};
labels = {'C_{n,Si}', 'C_{n,Gr}', 'C_n', 'C_p', 'LI', 's_V', 'U_{off}', 'MAE'};
param_colors = [
    0.2588 0.5059 0.6431
    0.6000 0.6000 0.6000
    0.7608 0.3882 0.2275
    0.4000 0.4000 0.4000
    0.2000 0.2000 0.2000
    0.4980 0.6941 0.8000
    0.1255 0.3647 0.4941
    0.8000 0.5059 0.3686
];
line_styles = {'-', '-', '-', '-', '-', ':', ':', '--'};

plot_sampling_panel(data, params, labels, param_colors, line_styles, false, ...
    fullfile(figure_dir, 'F5_b_sampling_error_bounds.svg'));
plot_sampling_panel(data, params, labels, param_colors, line_styles, true, ...
    fullfile(figure_dir, 'F5_b_sampling_error_bounds_loglog.svg'));

%% Helpers

function plot_sampling_panel(data, params, labels, param_colors, line_styles, use_loglog, output_file)
fig = figure('Position', [50, 50, 700, 300], 'Color', 'w');
hold on

for i = 1:numel(params)
    param = params{i};
    style = line_styles{i};
    if use_loglog
        style = '-';
    end
    plot(data.sample_points, data.(param), ...
        'Color', param_colors(i, :), ...
        'LineStyle', style, ...
        'Marker', 'o', ...
        'MarkerFaceColor', param_colors(i, :), ...
        'LineWidth', 0.8, ...
        'DisplayName', labels{i});
end

if use_loglog
    set(gca, 'XScale', 'log', 'YScale', 'log');
end
xlabel('Number of Sampling Points [-]');
ylabel('Error Bound [%]');

legend_handle = legend('Location', 'best');
legend_handle.FontSize = 16;
legend_handle.NumColumns = 2 + 2 * use_loglog;

ax = gca;
if ~use_loglog
    ax.YLim = [0, 13];
    ax.XLim = [0, 1000];
end
ax.FontSize = 20;
ax.XColor = [0.1 0.1 0.1];
ax.YColor = [0.1 0.1 0.1];
box on
grid off

set(fig, 'PaperPositionMode', 'auto');
print(fig, output_file, '-dsvg', '-vector');
end
