% Plot CRB-derived error bounds for selected SoC windows for Figure 5c.
%
% The input CSV is generated by code/error_bound_analysis/error_bound_analysis_with_CRB.ipynb.
% This panel summarizes representative partial-window cases; the contour-map
% companion panel is generated directly in code/error_bound_analysis.

clear
close all
clc

script_dir = fileparts(mfilename('fullpath'));
repo_root = fullfile(script_dir, '..', '..', '..');
crb_output_dir = fullfile(repo_root, 'code', 'error_bound_analysis', 'outputs');
figure_dir = fullfile(script_dir, 'figures');
if ~exist(figure_dir, 'dir')
    mkdir(figure_dir);
end

varied_data = readtable(fullfile(crb_output_dir, 'A03_SoC_Window_CRB_varied_inferred.csv'), 'ReadRowNames', true);
varied_data = varied_data(:, {'Cn_Si', 'Cn_Gr', 'Cn', 'Cp', 'LI', 'a', 'b'});
varied_data.MAE = mean(varied_data{:, {'Cn_Si', 'Cn_Gr', 'Cn', 'Cp', 'LI', 'a', 'b'}}, 2, 'omitnan');

param_names = {'C_{n,Si}', 'C_{n,Gr}', 'C_n', 'C_p', 'LI', 's_V', 'U_{off}', 'MAE'};
soc_window_labels = {'40-100%', '0-60%', '20-80%', '5-100%', '0-100%'};
data_matrix = table2array(varied_data(:, {'Cn_Si', 'Cn_Gr', 'Cn', 'Cp', 'LI', 'a', 'b', 'MAE'}));
[num_windows, num_params] = size(data_matrix);

param_colors = [
    0.2588 0.5059 0.6431
    0.6000 0.6000 0.6000
    0.7608 0.3882 0.2275
    0.4000 0.4000 0.4000
    0.2000 0.2000 0.2000
    0.4980 0.6941 0.8000
    0.1255 0.3647 0.4941
    0.8000 0.5059 0.3686
];

x = 1:num_windows;
bar_width = 0.11;

fig = figure('Position', [50, 50, 800, 300], 'Color', 'w');
hold on

for j = 1:num_params
    bar(x + (j - 1) * bar_width, data_matrix(:, j), ...
        bar_width, ...
        'FaceColor', param_colors(j, :), ...
        'FaceAlpha', 0.9, ...
        'EdgeColor', 'none', ...
        'DisplayName', param_names{j}, ...
        'LineWidth', 0.5);
end

xticks(x + (num_params - 1) * bar_width / 2);
xticklabels(soc_window_labels);
xlim([x(1) - 5 * bar_width, x(end) + (num_params + 5) * bar_width]);
xlabel('Selected SoC Window [-]');
ylabel('Error Bound [%]');

ax = gca;
ax.YLim = [0, 12];
ax.FontSize = 18;
ax.XColor = [0.1 0.1 0.1];
ax.YColor = [0.1 0.1 0.1];
legend('Location', 'northeast', 'NumColumns', 2);
grid off
box on

set(fig, 'PaperPositionMode', 'auto');
print(fig, fullfile(figure_dir, 'F5_c_1_soc_window_error_bounds.svg'), '-dsvg', '-vector');
