% Plot the minimum-data requirement from the sampling-frequency CRB study.
%
% The input CSV is generated by error_bound_analysis_with_CRB.ipynb. Each
% column reports the 95% Cramer-Rao error bound, expressed as a percentage of
% the nominal eSOH quantity, for a different number of sampled voltage points.
% The sweep is evaluated over the full 0--100% SoC window and supports the
% 8-points-per-SoC downsampling choice used in the paper.

close all

script_dir = fileparts(mfilename('fullpath'));
output_dir = fullfile(script_dir, 'outputs');
figure_dir = fullfile(output_dir, 'figures');
if ~exist(figure_dir, 'dir')
    mkdir(figure_dir);
end

data = readtable(fullfile(output_dir, 'A03_Sampling_Points_Impact_BOL_inferred.csv'));

% Mean error bound across the five transformed diagnostic parameters and the
% two silicon-OCP deformation parameters.
data.MAE = mean([data.Cn_Si, data.Cn_Gr, data.Cn, data.Cp, data.LI, data.a, data.b], 2, 'omitnan');

% Consistent parameter colors used across the error-bound panels.
param_colors = [
    0.2588 0.5059 0.6431;  % C_{n,Si}
    0.6000 0.6000 0.6000;  % C_{n,Gr}
    0.7608 0.3882 0.2275;  % C_n
    0.4000 0.4000 0.4000;  % C_p
    0.2000 0.2000 0.2000;  % LI
    0.4980 0.6941 0.8000;  % a
    0.1255    0.3647    0.4941;  % b
    0.8000    0.5059    0.3686;  % MAE
];

colorMap = struct( ...
    'Cn_Si', param_colors(1,:), ...
    'Cn_Gr', param_colors(2,:), ...
    'Cn',    param_colors(3,:), ...
    'Cp',    param_colors(4,:), ...
    'LI',    param_colors(5,:), ...
    'MAE',   param_colors(8,:), ...
    'a',    param_colors(6,:), ...
    'b',   param_colors(7,:) ...
);

linestyleMap = struct( ...
    'Cn_Si', '-', ...
    'Cn_Gr', '-', ...
    'Cn',    '-', ...
    'Cp',    '-', ...
    'LI',    '-', ...
    'MAE',   '--', ...
    'a',    ':', ...
    'b',   ':' ...
);

params = {'Cn_Si','Cn_Gr','Cn','Cp','LI','a','b','MAE'};
labels = {'C_{n,Si}','C_{n,Gr}','C_n','C_p','LI','s_V','U_{off}','MAE'};

%% Linear-scale error bounds for the sampling-density sweep
figure('Position', [50, 50, 700, 300]); hold on;
for i = 1:numel(params)
    p = params{i};
    plot(data.sample_points, data.(p), ...
        'Color', colorMap.(p), ...
        'LineStyle', linestyleMap.(p), ...
        'Marker', 'o', ...
        'MarkerFaceColor', colorMap.(p), ...
        'LineWidth', 0.5, ...
        'DisplayName', labels{i});
end
xlabel('Number of Sampling Points [-]', 'FontSize', 14);
ylabel('Error Bound [%]', 'FontSize', 14);
grid on; set(gca, 'XGrid', 'on', 'YGrid', 'on', 'GridLineStyle', '--');

l = legend('Location','best');
l.FontSize = 16;
l.NumColumns = 2;

ax = gca;
ax.YLim = [0, 13];
ax.XLim = [0,1000];
ax.FontSize = 20;
ax.XColor = [0.1 0.1 0.1];
ax.YColor = [0.1 0.1 0.1];
box on; grid off
set(gcf,'color','w');
print(gcf, fullfile(figure_dir, 'A03_1_1.svg'), '-dsvg', '-vector');

%% Log-log trend used to assess diminishing returns with added samples
figure('Position', [50, 50, 600, 300]); hold on;
for i = 1:numel(params)
    p = params{i};
    plot(data.sample_points, data.(p), ...
        'Color', colorMap.(p), ...
        'LineStyle', '-', ...
        'Marker', 'o', ...
        'MarkerFaceColor', colorMap.(p), ...
        'LineWidth', 1.2, ...
        'DisplayName', labels{i});
end
set(gca, 'XScale', 'log', 'YScale', 'log');
xlabel('Number of Sampling Points [-]', 'FontSize', 14);
ylabel('Error Bound [%]', 'FontSize', 14);

l = legend('Location','best');
l.FontSize = 16;
l.NumColumns = 4;

grid on; set(gca, 'XGrid', 'on', 'YGrid', 'on', 'GridLineStyle', '--');

ax = gca;
ax.FontSize = 20;
ax.XColor = [0.1 0.1 0.1];
ax.YColor = [0.1 0.1 0.1];
grid off; box on
set(gcf,'color','w');
print(gcf, fullfile(figure_dir, 'A03_1_2.svg'), '-dsvg', '-vector');
