% Plot CRB-derived error bounds for selected SoC measurement windows.
%
% The input CSV is generated by error_bound_analysis_with_CRB.ipynb. Rows
% correspond to candidate SoC windows and columns correspond to propagated eSOH
% quantities. The grouped bars compare which windows best constrain each
% parameter at the 8-points-per-SoC sampling density used in the paper. These
% results identify which partial charge windows remain valid when a full
% 0--100% SoC diagnostic trace is unavailable.

close all

script_dir = fileparts(mfilename('fullpath'));
output_dir = fullfile(script_dir, 'outputs');
figure_dir = fullfile(output_dir, 'figures');
if ~exist(figure_dir, 'dir')
    mkdir(figure_dir);
end

varied_data = readtable(fullfile(output_dir, 'A03_SoC_Window_CRB_varied_inferred.csv'), 'ReadRowNames', true);

% Keep the reported quantities in the order used for the SoC-window comparison.
varied_data = varied_data(:, {'Cn_Si','Cn_Gr','Cn','Cp','LI','a','b'});

% Mean error bound across the five transformed diagnostic parameters and the
% two silicon-OCP deformation parameters.
varied_data.MAE = mean(varied_data{:, {'Cn_Si','Cn_Gr','Cn','Cp','LI','a','b'}}, 2, 'omitnan');

param_names = {'C_{n,Si}','C_{n,Gr}','C_n','C_p','LI','s_V','U_{off}','MAE'};
soc_window_labels = {'40-100%','0-60%','20-80%','5-100%','0-100%'};

D = table2array(varied_data(:, {'Cn_Si','Cn_Gr','Cn','Cp','LI','a','b','MAE'}));
[num_windows, num_params] = size(D);

x = 1:num_windows;

bar_width = 0.11;
opacity   = 0.9;

% Consistent parameter colors used across the error-bound panels.
param_colors = [
    0.2588 0.5059 0.6431;  % C_{n,Si}
    0.6000 0.6000 0.6000;  % C_{n,Gr}
    0.7608 0.3882 0.2275;  % C_n
    0.4000 0.4000 0.4000;  % C_p
    0.2000 0.2000 0.2000;  % LI
    0.4980 0.6941 0.8000;  % a
    0.1255    0.3647    0.4941;  % b
    0.8000    0.5059    0.3686;  % MAE
];

figure('Position', [50, 50, 800, 300]); 
hold on;

for j = 1:num_params
    bar(x + (j-1)*bar_width, D(:, j), ...
        bar_width, ...
        'FaceColor', param_colors(j, :), ...
        'FaceAlpha', opacity, ...
        'EdgeColor', 'none', ...
        'DisplayName', param_names{j}, ...
        'LineWidth', 0.5);
end

xticks(x + (num_params-1)*bar_width/2);
xticklabels(soc_window_labels);

left_edge  = x(1) - 5*bar_width;
right_edge = x(end) + (num_params+5)*bar_width;
xlim([left_edge, right_edge]);

xlabel('Selected SoC Window [-]', 'FontSize', 20, 'Color', [0.1 0.1 0.1]);
ylabel('Error Bound [%]', 'FontSize', 20, 'Color', [0.1 0.1 0.1]);
set(gca, 'FontSize', 18, 'XColor', [0.1 0.1 0.1], 'YColor', [0.1 0.1 0.1]);

ax = gca; 
ax.YLim = [0, 12];

legend('Location','northeast','NumColumns',2);

grid off; 
box on; 
set(gcf, 'color', 'w');

print(gcf, fullfile(figure_dir, 'A03_2_2_reverse_with_MAE_Cn.svg'), '-dsvg', '-vector');
hold off;
